### PR TITLE
Externalized session handling and opened up for frontend/backend deployments

### PR DESCRIPTION
**Pull request by martin-lindstrom**
The SignService code no longer relies on the Java Servlet API...

### CODE REVIEW

**Review by Razumain — COMMENTED** [review]
I ave reviewed the approach which seems great in general.

My only thought and question is whether it is a good idea to do JSON serialisation of the HTTP request. This will expand the size of data being transmitted. This may not be a problem as such since we do not send the document to be signed, but a binary serialisation with compression could be implemented with reasonable effort.

**Review by Razumain — APPROVED** [review]
Changing to approve.  JSON is a great start for serialisation.

**Review by nod9 — APPROVED** [review]
Nice work!

One small thought, should we use RestTemple? Not really an issue here as it used in the demo app

**Comment by martin-lindstrom** [comment]
> Nice work!
> 
> One small thought, should we use RestTemple? Not really an issue here as it used in the demo app

I know that WebClient is the choice to use, but it is more complex to set up and not as obvious in examples, so I used RestTemplate.

**Pull request merged**
